# action.yml
name: 'tethys-app-linter'
description: 'A GitHub Action to check the code integrity of Tethys applications.'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  repository:
    description: 'The Tethys app repository to lint.'
    required: true
    default: ${{ github.repository }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repository }}
