# action.yml
name: 'tethys-app-linter'
description: 'A GitHub Action to check the code integrity of Tethys applications.'
inputs:
  repository:
    description: 'The Tethys app repository to lint.'
    required: true
    default: ${{ github.repository }}
outputs:
  success:
    description: 'Returns "success" if all checks pass, "failed" if not.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repository }}
