name: tethys-app-linter

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run tethys-app-linter
      uses: Aquaveo/tethys-app-linter@v1
